---
- name: Restart sshd
  ansible.builtin.shell: |
    if systemctl is-active ssh.socket > /dev/null 2>&1; then
      systemctl daemon-reload
      systemctl restart ssh.socket
    fi
    systemctl restart ssh
  changed_when: true

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    enabled: true

- name: Restart auditd
  ansible.builtin.command:
    cmd: service auditd restart
  changed_when: true
