---
- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
    enabled: true

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    enabled: true

- name: Restart auditd
  ansible.builtin.systemd:
    name: auditd
    state: restarted
    enabled: true
