---
python_pyenv_root: /opt/pyenv
python_pyenv_version: "v2.4.22"
python_version: "3.12.8"
python_symlink_dir: /usr/local/bin
python_pyenv_commit_sha: ""
python_build_deps:
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev
