---
- name: Restart systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
    enabled: true

- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
