---
- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: true

- name: Reload audit rules
  ansible.builtin.command:
    cmd: service auditd restart
  changed_when: true
