---
- name: Full convergence
  ansible.builtin.import_playbook: setup_system.yml

- name: Full convergence
  ansible.builtin.import_playbook: setup_services.yml

- name: Full convergence
  ansible.builtin.import_playbook: setup_toolchain.yml

- name: Full convergence
  ansible.builtin.import_playbook: deploy_openclaw.yml

- name: Full convergence
  ansible.builtin.import_playbook: update_nginx.yml
