---
- name: Restart tailscaled
  ansible.builtin.systemd:
    name: tailscaled
    state: restarted
    enabled: true

- name: Reload audit rules
  ansible.builtin.command:
    cmd: service auditd restart
  changed_when: true
