---
- name: Create and configure OpenClaw user
  ansible.builtin.import_tasks: user.yml

# - name: Install OpenClaw
#   ansible.builtin.import_tasks: install.yml

# - name: Configure OpenClaw
#   ansible.builtin.import_tasks: configure.yml

# - name: Deploy OpenClaw systemd service
#   ansible.builtin.import_tasks: systemd.yml

# - name: Configure Tailscale Serve for OpenClaw
#   ansible.builtin.include_tasks: tailscale_serve.yml

# - name: Run OpenClaw health check
#   ansible.builtin.import_tasks: health_check.yml
